//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_BARRA
    {
        public int ncode_barra { get; set; }
        public string sdesc_barra { get; set; }
        public bool nesta_barra { get; set; }
        public long ncode_arti { get; set; }
        public string suser_barra { get; set; }
        public Nullable<System.DateTime> dfech_barra { get; set; }
        public string susmo_barra { get; set; }
        public Nullable<System.DateTime> dfemo_barra { get; set; }
    
        public virtual ARTICULO ARTICULO { get; set; }
    }
}
