//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLI_FOPAGO
    {
        public Nullable<int> ncode_fopago { get; set; }
        public Nullable<int> ncode_cliente { get; set; }
        public Nullable<System.DateTime> dfech_clifo { get; set; }
        public string susuer_clifo { get; set; }
        public Nullable<System.DateTime> dfemo_clifo { get; set; }
        public string susmo_clifo { get; set; }
        public long ncode_clifo { get; set; }
    
        public virtual CONFIGURACION CONFIGURACION { get; set; }
        public virtual CLIENTE CLIENTE { get; set; }
    }
}
