//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPRA_DETALLE
    {
        public long ncode_comdeta { get; set; }
        public Nullable<decimal> ncant_comdeta { get; set; }
        public Nullable<decimal> npu_comdeta { get; set; }
        public Nullable<decimal> ndscto_comdeta { get; set; }
        public Nullable<decimal> ndscto2_comdeta { get; set; }
        public Nullable<decimal> nexon_comdeta { get; set; }
        public Nullable<decimal> nafecto_comdeta { get; set; }
        public Nullable<bool> besafecto_comdeta { get; set; }
        public Nullable<int> nback_comdeta { get; set; }
        public long ncode_compra { get; set; }
        public int ncode_alma { get; set; }
        public long ncode_arti { get; set; }
        public Nullable<decimal> nsubt_comdeta { get; set; }
        public Nullable<decimal> ncantLote_comdeta { get; set; }
        public Nullable<int> norden_comdeta { get; set; }
        public Nullable<long> ncode_orco { get; set; }
    
        public virtual ALMACEN ALMACEN { get; set; }
        public virtual COMPRAS COMPRAS { get; set; }
        public virtual ARTICULO ARTICULO { get; set; }
    }
}
