//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTASPA_DETALLE
    {
        public long ncode_ctapade { get; set; }
        public Nullable<System.DateTime> dfepago_ctapade { get; set; }
        public string smone_ctapade { get; set; }
        public Nullable<decimal> ntc_ctapade { get; set; }
        public Nullable<decimal> nmonto_ctapade { get; set; }
        public string sobse_ctapade { get; set; }
        public Nullable<decimal> nvuelto_ctapade { get; set; }
        public string suser_ctapade { get; set; }
        public Nullable<System.DateTime> dfech_ctapade { get; set; }
        public string susmo_ctapade { get; set; }
        public Nullable<System.DateTime> dfemo_ctapade { get; set; }
        public string suser_tarjeta { get; set; }
        public string snro_tarjeta { get; set; }
        public long ncode_ctapa { get; set; }
        public Nullable<int> ncode_banco { get; set; }
        public int ncode_tpago { get; set; }
    
        public virtual CTAS_PAGAR CTAS_PAGAR { get; set; }
        public virtual CONFIGURACION CONFIGURACION { get; set; }
        public virtual CONFIGURACION CONFIGURACION1 { get; set; }
    }
}
