//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCU_SERIE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DOCU_SERIE()
        {
            this.DOCU_SERIE_USUARIO = new HashSet<DOCU_SERIE_USUARIO>();
        }
    
        public long ncode_dose { get; set; }
        public int ncode_docu { get; set; }
        public string snumeracion_dose { get; set; }
        public string susuario_dose { get; set; }
        public string sdocumento_dose { get; set; }
        public string suser_dose { get; set; }
        public Nullable<System.DateTime> dfech_dose { get; set; }
        public string susmo_dose { get; set; }
        public Nullable<System.DateTime> dfemo_dose { get; set; }
        public int ncode_local { get; set; }
        public string sserie_dose { get; set; }
        public Nullable<bool> besta_dose { get; set; }
    
        public virtual CONFIGURACION CONFIGURACION { get; set; }
        public virtual LOCAL LOCAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOCU_SERIE_USUARIO> DOCU_SERIE_USUARIO { get; set; }
    }
}
