//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCU_SERIE_USUARIO
    {
        public Nullable<long> ncode_dose { get; set; }
        public string susuario_dose { get; set; }
        public string suser_dose { get; set; }
        public Nullable<System.DateTime> dfech_dose { get; set; }
        public string susmo_dose { get; set; }
        public Nullable<System.DateTime> dfemo_dose { get; set; }
        public long ncode_docuus { get; set; }
    
        public virtual DOCU_SERIE DOCU_SERIE { get; set; }
    }
}
