//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESPECIE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ESPECIE()
        {
            this.ARTICULO = new HashSet<ARTICULO>();
        }
    
        public long ncode_espe { get; set; }
        public string sdesc_espe { get; set; }
        public Nullable<bool> nesta_espe { get; set; }
        public string suser_espe { get; set; }
        public Nullable<System.DateTime> dfech_espe { get; set; }
        public string susmo_espe { get; set; }
        public Nullable<System.DateTime> dfemo_espe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARTICULO> ARTICULO { get; set; }
    }
}
