//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GUIA_CUOTAS
    {
        public long ncode_guiacu { get; set; }
        public Nullable<long> ncode_guia { get; set; }
        public Nullable<System.DateTime> dfreg_guiacu { get; set; }
        public Nullable<decimal> nvalor_guiacu { get; set; }
        public Nullable<System.DateTime> dfech_guiacu { get; set; }
        public Nullable<System.DateTime> dfemo_guiacu { get; set; }
        public string suser_guiacu { get; set; }
        public string susmo_guiacu { get; set; }
    
        public virtual GUIA GUIA { get; set; }
    }
}
