//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LISTA_PRECIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LISTA_PRECIO()
        {
            this.ART_PRECIO = new HashSet<ART_PRECIO>();
        }
    
        public int ncode_lipre { get; set; }
        public string sdesc_lipre { get; set; }
        public bool nesta_lipre { get; set; }
        public string suser_lipre { get; set; }
        public Nullable<System.DateTime> dfech_lipre { get; set; }
        public string susmo_lipre { get; set; }
        public Nullable<System.DateTime> dfemo_lipre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ART_PRECIO> ART_PRECIO { get; set; }
    }
}
