//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROV_CONTACTO
    {
        public int ncode_provcontac { get; set; }
        public long ncode_provee { get; set; }
        public int ncode_contac { get; set; }
        public Nullable<int> besta_provcontac { get; set; }
    
        public virtual CONTACTO CONTACTO { get; set; }
        public virtual PROVEEDOR PROVEEDOR { get; set; }
    }
}
