//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_GUIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIPO_GUIA()
        {
            this.GUIA = new HashSet<GUIA>();
        }
    
        public int ncode_tiguia { get; set; }
        public string sdesc_tiguia { get; set; }
        public bool binout_tiguia { get; set; }
        public bool btransf_tiguia { get; set; }
        public bool besta_tiguia { get; set; }
        public string stipo_tiguia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GUIA> GUIA { get; set; }
    }
}
