//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSPORTISTA
    {
        public long ncode_tran { get; set; }
        public string snomb_tran { get; set; }
        public string sappa_tran { get; set; }
        public string sapma_tran { get; set; }
        public string splaca_tran { get; set; }
        public string sdni_tran { get; set; }
        public string slicencia_tran { get; set; }
        public string suser_tran { get; set; }
        public Nullable<System.DateTime> dfech_tran { get; set; }
        public string susmo_tran { get; set; }
        public Nullable<System.DateTime> dfemo_tran { get; set; }
        public Nullable<bool> nesta_tran { get; set; }
    }
}
