//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENDEDOR_ZONA
    {
        public Nullable<long> ncode_vende { get; set; }
        public Nullable<long> ncode_zona { get; set; }
        public long ncode_venzo { get; set; }
        public Nullable<bool> nesta_venzo { get; set; }
        public Nullable<System.DateTime> dfech_venzo { get; set; }
        public string suser_venzo { get; set; }
        public Nullable<System.DateTime> dfemo_venzo { get; set; }
        public string susmo_venzo { get; set; }
    
        public virtual VENDEDOR VENDEDOR { get; set; }
        public virtual ZONA ZONA { get; set; }
    }
}
