//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketASP.Areas.Administracion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONFIGURACION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONFIGURACION()
        {
            this.DOCU_SERIE = new HashSet<DOCU_SERIE>();
        }
    
        public int ncode_confi { get; set; }
        public string sdesc_confi { get; set; }
        public string svalor_confi { get; set; }
        public bool besta_confi { get; set; }
        public int ntipo_confi { get; set; }
        public string stipo_confi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOCU_SERIE> DOCU_SERIE { get; set; }
    }
}
