//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketASP.Areas.Administracion.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MarketWebEntitiesAdmin : DbContext
    {
        public MarketWebEntitiesAdmin()
            : base("name=MarketWebEntitiesAdmin")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Permiso> Permiso { get; set; }
        public virtual DbSet<Ventana> Ventana { get; set; }
        public virtual DbSet<LOCAL> LOCAL { get; set; }
        public virtual DbSet<CONFIGURACION> CONFIGURACION { get; set; }
        public virtual DbSet<DOCU_SERIE> DOCU_SERIE { get; set; }
    
        public virtual int Pr_PermisoCrear(string username, string nivel)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var nivelParameter = nivel != null ?
                new ObjectParameter("nivel", nivel) :
                new ObjectParameter("nivel", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_PermisoCrear", usernameParameter, nivelParameter);
        }
    
        public virtual int Pr_PermisoEliminar(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_PermisoEliminar", usernameParameter);
        }
    
        public virtual ObjectResult<Pr_PermisoLista_Result> Pr_PermisoLista(string usuario)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_PermisoLista_Result>("Pr_PermisoLista", usuarioParameter);
        }
    }
}
