//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_PRECIO
    {
        public int ncode_artpre { get; set; }
        public Nullable<decimal> nprecio_artpre { get; set; }
        public Nullable<bool> nesta_artpre { get; set; }
        public int ncode_lipre { get; set; }
        public int ncode_arti { get; set; }
        public string suser_artpre { get; set; }
        public Nullable<System.DateTime> dfech_artpre { get; set; }
        public string susmo_artpre { get; set; }
        public Nullable<System.DateTime> dfemo_artpre { get; set; }
    
        public virtual LISTA_PRECIO LISTA_PRECIO { get; set; }
        public virtual ARTICULO ARTICULO { get; set; }
    }
}
