//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_PROVE
    {
        public int ncode_arprove { get; set; }
        public Nullable<long> ncode_provee { get; set; }
        public long ncode_arti { get; set; }
        public string suser_arprove { get; set; }
        public Nullable<System.DateTime> dfech_arprove { get; set; }
        public string susmo_arprove { get; set; }
        public Nullable<System.DateTime> dfemo_arprove { get; set; }
    
        public virtual ARTICULO ARTICULO { get; set; }
        public virtual PROVEEDOR PROVEEDOR { get; set; }
    }
}
