//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_BARRA
    {
        public int ncode_barra { get; set; }
        public string sdesc_barra { get; set; }
        public bool nesta_barra { get; set; }
        public long ncode_arti { get; set; }
        public string suser_barra { get; set; }
        public Nullable<System.DateTime> dfech_barra { get; set; }
        public string susmo_barra { get; set; }
        public Nullable<System.DateTime> dfemo_barra { get; set; }
    
        public virtual ARTICULO ARTICULO { get; set; }
    }
}
