//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_PROVE
    {
        public int ncode_arprove { get; set; }
        public Nullable<long> ncode_provee { get; set; }
        public long ncode_arti { get; set; }
        public string suser_arprove { get; set; }
        public Nullable<System.DateTime> dfech_arprove { get; set; }
        public string susmo_arprove { get; set; }
        public Nullable<System.DateTime> dfemo_arprove { get; set; }
    
        public virtual ARTICULO ARTICULO { get; set; }
        public virtual PROVEEDOR PROVEEDOR { get; set; }
    }
}
