//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_PRECIO
    {
        public int ncode_artpre { get; set; }
        public Nullable<decimal> nprecio_artpre { get; set; }
        public bool nesta_artpre { get; set; }
        public int ncode_lipre { get; set; }
        public long ncode_arti { get; set; }
        public string suser_artpre { get; set; }
        public Nullable<System.DateTime> dfech_artpre { get; set; }
        public string susmo_artpre { get; set; }
        public Nullable<System.DateTime> dfemo_artpre { get; set; }
    
        public virtual LISTA_PRECIO LISTA_PRECIO { get; set; }
        public virtual ARTICULO ARTICULO { get; set; }
    }
}
