//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARTICULO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ARTICULO()
        {
            this.ART_BARRA = new HashSet<ART_BARRA>();
            this.ART_PRECIO = new HashSet<ART_PRECIO>();
            this.ART_PROVE = new HashSet<ART_PROVE>();
            this.KARDEX = new HashSet<KARDEX>();
            this.VENTA_DETALLE = new HashSet<VENTA_DETALLE>();
            this.COMPRA_DETALLE = new HashSet<COMPRA_DETALLE>();
            this.PROFORMA_DETALLE = new HashSet<PROFORMA_DETALLE>();
            this.ORDEN_PEDIDOS_DETALLE = new HashSet<ORDEN_PEDIDOS_DETALLE>();
            this.ORDEN_COMPRAS_DETALLE = new HashSet<ORDEN_COMPRAS_DETALLE>();
            this.LOTES = new HashSet<LOTES>();
            this.GUIA_DETALLE = new HashSet<GUIA_DETALLE>();
            this.VENTA_LOTE = new HashSet<VENTA_LOTE>();
            this.GUIA_LOTE = new HashSet<GUIA_LOTE>();
            this.MOVI_DETALLE = new HashSet<MOVI_DETALLE>();
            this.MOVI_LOTE = new HashSet<MOVI_LOTE>();
            this.RecetaDetalle = new HashSet<RecetaDetalle>();
            this.FabricacionDetalle = new HashSet<FabricacionDetalle>();
        }
    
        public long ncode_arti { get; set; }
        public string sdesc1_arti { get; set; }
        public string sdesc2_arti { get; set; }
        public string sdescweb_arti { get; set; }
        public string scode_arti { get; set; }
        public Nullable<long> ncode_fami { get; set; }
        public Nullable<long> ncode_clase { get; set; }
        public Nullable<long> ncode_marca { get; set; }
        public Nullable<long> ncode_umed { get; set; }
        public Nullable<bool> bisc_arti { get; set; }
        public Nullable<bool> bafecto_arti { get; set; }
        public Nullable<bool> bivap_arti { get; set; }
        public Nullable<bool> bpercepcion_arti { get; set; }
        public Nullable<decimal> nporpercepcion_arti { get; set; }
        public Nullable<bool> bvenc_arti { get; set; }
        public string sserie_arti { get; set; }
        public string sobse_arti { get; set; }
        public bool nesta_arti { get; set; }
        public Nullable<decimal> nstockmin_arti { get; set; }
        public Nullable<decimal> nstockmax_arti { get; set; }
        public string sabrev_arti { get; set; }
        public Nullable<bool> bdscto_arti { get; set; }
        public string spaisOrigen_arti { get; set; }
        public Nullable<bool> bprocedencia_arti { get; set; }
        public string suser_arti { get; set; }
        public Nullable<System.DateTime> dfech_arti { get; set; }
        public string susmo_arti { get; set; }
        public Nullable<System.DateTime> dfemo_arti { get; set; }
        public Nullable<bool> bicbper_arti { get; set; }
        public string scodsunat_arti { get; set; }
        public string stipomerca_arti { get; set; }
        public string scodectadebe_ventas { get; set; }
        public string ctadebe_ventas { get; set; }
        public string scodectahaber_ventas { get; set; }
        public string ctahaber_ventas { get; set; }
        public string scodectadebe_compras { get; set; }
        public string ctadebe_compras { get; set; }
        public string scodectahaber_compras { get; set; }
        public string ctahaber_compras { get; set; }
        public string scodigo_sap { get; set; }
        public string sorigen { get; set; }
        public string snombre_equivalencia { get; set; }
        public string sequivalenciaA { get; set; }
        public string sequivalenciaB { get; set; }
        public string smoneda { get; set; }
        public Nullable<decimal> nstockactual { get; set; }
        public Nullable<bool> bdetraccion { get; set; }
        public Nullable<decimal> porcdetraccion { get; set; }
        public string codigodetraccion { get; set; }
        public string snombrepalletcaja { get; set; }
        public string spallet { get; set; }
        public string sbandeja { get; set; }
        public Nullable<long> ncode_linea { get; set; }
        public Nullable<long> ncode_sublinea { get; set; }
        public Nullable<decimal> nprecio_arti { get; set; }
        public Nullable<decimal> nstockreservado_arti { get; set; }
        public Nullable<long> ncode_espe { get; set; }
        public Nullable<long> ncode_subesp { get; set; }
        public Nullable<decimal> npreciotope_arti { get; set; }
        public Nullable<decimal> nmargen_arti { get; set; }
        public Nullable<decimal> ncosto_arti { get; set; }
        public Nullable<decimal> nultcosto_arti { get; set; }
        public Nullable<bool> blote_arti { get; set; }
        public Nullable<decimal> nstocktransito_arti { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ART_BARRA> ART_BARRA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ART_PRECIO> ART_PRECIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ART_PROVE> ART_PROVE { get; set; }
        public virtual ESPECIE ESPECIE { get; set; }
        public virtual SUBESPECIE SUBESPECIE { get; set; }
        public virtual FAMILIA FAMILIA { get; set; }
        public virtual CLASE CLASE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KARDEX> KARDEX { get; set; }
        public virtual MARCA MARCA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VENTA_DETALLE> VENTA_DETALLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPRA_DETALLE> COMPRA_DETALLE { get; set; }
        public virtual UMEDIDA UMEDIDA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROFORMA_DETALLE> PROFORMA_DETALLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDEN_PEDIDOS_DETALLE> ORDEN_PEDIDOS_DETALLE { get; set; }
        public virtual LINEA LINEA { get; set; }
        public virtual SUBLINEA SUBLINEA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDEN_COMPRAS_DETALLE> ORDEN_COMPRAS_DETALLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOTES> LOTES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GUIA_DETALLE> GUIA_DETALLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VENTA_LOTE> VENTA_LOTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GUIA_LOTE> GUIA_LOTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MOVI_DETALLE> MOVI_DETALLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MOVI_LOTE> MOVI_LOTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecetaDetalle> RecetaDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FabricacionDetalle> FabricacionDetalle { get; set; }
    }
}
