//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARTICULO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ARTICULO()
        {
            this.ART_BARRA = new HashSet<ART_BARRA>();
            this.ART_PRECIO = new HashSet<ART_PRECIO>();
            this.ART_PROVE = new HashSet<ART_PROVE>();
        }
    
        public int ncode_arti { get; set; }
        public string sdesc1_arti { get; set; }
        public string sdesc2_arti { get; set; }
        public string sdescweb_arti { get; set; }
        public string scode_arti { get; set; }
        public Nullable<int> ncode_fami { get; set; }
        public Nullable<int> ncode_clase { get; set; }
        public Nullable<int> ncode_marca { get; set; }
        public Nullable<int> ncode_umed { get; set; }
        public Nullable<bool> bisc_arti { get; set; }
        public Nullable<bool> bafecto_arti { get; set; }
        public Nullable<bool> bivap_arti { get; set; }
        public Nullable<bool> bpercepcion_arti { get; set; }
        public Nullable<decimal> nporpercepcion_arti { get; set; }
        public Nullable<bool> bvenc_arti { get; set; }
        public string sserie_arti { get; set; }
        public string sobse_arti { get; set; }
        public bool nesta_arti { get; set; }
        public Nullable<decimal> nstockmin_arti { get; set; }
        public Nullable<decimal> nstockmax_arti { get; set; }
        public string sabrev_arti { get; set; }
        public Nullable<bool> bdscto_arti { get; set; }
        public string spaisOrigen_arti { get; set; }
        public Nullable<bool> bprocedencia_arti { get; set; }
        public string suser_arti { get; set; }
        public Nullable<System.DateTime> dfech_arti { get; set; }
        public string susmo_arti { get; set; }
        public Nullable<System.DateTime> dfemo_arti { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ART_BARRA> ART_BARRA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ART_PRECIO> ART_PRECIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ART_PROVE> ART_PROVE { get; set; }
        public virtual FAMILIA FAMILIA { get; set; }
        public virtual CLASE CLASE { get; set; }
        public virtual MARCA MARCA { get; set; }
        public virtual UMEDIDA UMEDIDA { get; set; }
    }
}
