//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLASE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLASE()
        {
            this.ARTICULO = new HashSet<ARTICULO>();
        }
    
        public int ncode_clase { get; set; }
        public string sdesc_clase { get; set; }
        public Nullable<bool> nesta_clase { get; set; }
        public Nullable<int> ncode_fami { get; set; }
        public string suser_clase { get; set; }
        public Nullable<System.DateTime> dfech_clase { get; set; }
        public string susmo_clase { get; set; }
        public Nullable<System.DateTime> dfemo_clase { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARTICULO> ARTICULO { get; set; }
        public virtual FAMILIA FAMILIA { get; set; }
    }
}
