//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLASE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLASE()
        {
            this.ARTICULO = new HashSet<ARTICULO>();
        }
    
        public long ncode_clase { get; set; }
        public string sdesc_clase { get; set; }
        public bool nesta_clase { get; set; }
        public Nullable<long> ncode_fami { get; set; }
        public string suser_clase { get; set; }
        public Nullable<System.DateTime> dfech_clase { get; set; }
        public string susmo_clase { get; set; }
        public Nullable<System.DateTime> dfemo_clase { get; set; }
    
        public virtual FAMILIA FAMILIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARTICULO> ARTICULO { get; set; }
    }
}
