//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLI_FOPAGO
    {
        public Nullable<int> ncode_fopago { get; set; }
        public Nullable<int> ncode_cliente { get; set; }
        public Nullable<System.DateTime> dfech_clifo { get; set; }
        public string susuer_clifo { get; set; }
        public Nullable<System.DateTime> dfemo_clifo { get; set; }
        public string susmo_clifo { get; set; }
        public long ncode_clifo { get; set; }
    
        public virtual CONFIGURACION CONFIGURACION { get; set; }
        public virtual CLIENTE CLIENTE { get; set; }
    }
}
