//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIDI_CONTAC
    {
        public int ncode_clidco { get; set; }
        public int ncode_clidire { get; set; }
        public int ncode_contac { get; set; }
        public bool besta_clidco { get; set; }
    
        public virtual CLI_DIRE CLI_DIRE { get; set; }
        public virtual CONTACTO CONTACTO { get; set; }
    }
}
