//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIDI_CONTAC
    {
        public int ncode_clidco { get; set; }
        public int ncode_clidire { get; set; }
        public int ncode_contac { get; set; }
        public bool besta_clidco { get; set; }
    
        public virtual CLI_DIRE CLI_DIRE { get; set; }
        public virtual CONTACTO CONTACTO { get; set; }
    }
}
