//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPRA_DETALLE
    {
        public long ncode_comdeta { get; set; }
        public Nullable<decimal> ncant_comdeta { get; set; }
        public Nullable<decimal> npu_comdeta { get; set; }
        public Nullable<decimal> ndscto_comdeta { get; set; }
        public Nullable<decimal> ndscto2_comdeta { get; set; }
        public Nullable<decimal> nexon_comdeta { get; set; }
        public Nullable<decimal> nafecto_comdeta { get; set; }
        public Nullable<bool> besafecto_comdeta { get; set; }
        public Nullable<int> nback_comdeta { get; set; }
        public long ncode_compra { get; set; }
        public int ncode_alma { get; set; }
        public long ncode_arti { get; set; }
        public Nullable<decimal> nsubt_comdeta { get; set; }
        public Nullable<decimal> ncantLote_comdeta { get; set; }
    
        public virtual ALMACEN ALMACEN { get; set; }
        public virtual COMPRAS COMPRAS { get; set; }
        public virtual ARTICULO ARTICULO { get; set; }
    }
}
