//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTACTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONTACTO()
        {
            this.CLIDI_CONTAC = new HashSet<CLIDI_CONTAC>();
            this.PROV_CONTACTO = new HashSet<PROV_CONTACTO>();
        }
    
        public int ncode_contac { get; set; }
        public string snomb_contac { get; set; }
        public string sappa_contac { get; set; }
        public string sapma_contac { get; set; }
        public string scargo_contac { get; set; }
        public string sfono1_contac { get; set; }
        public string sfono2_contac { get; set; }
        public string smail_contac { get; set; }
        public string suser_contac { get; set; }
        public Nullable<System.DateTime> dfech_contac { get; set; }
        public string susmo_contac { get; set; }
        public Nullable<System.DateTime> dfemo_contac { get; set; }
        public bool besta_contac { get; set; }
        public string stipo_contac { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIDI_CONTAC> CLIDI_CONTAC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROV_CONTACTO> PROV_CONTACTO { get; set; }
    }
}
