//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTA_COBRAR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CTA_COBRAR()
        {
            this.CTASCO_DETALLE = new HashSet<CTASCO_DETALLE>();
        }
    
        public long ncode_ctaco { get; set; }
        public Nullable<long> ncodeDoc_ctaco { get; set; }
        public string sdocu_ctaco { get; set; }
        public Nullable<System.DateTime> dfecta_ctaco { get; set; }
        public string smone_ctaco { get; set; }
        public Nullable<decimal> ntotal_ctaco { get; set; }
        public Nullable<System.DateTime> dfevenci_ctaco { get; set; }
        public Nullable<decimal> ntc_ctaco { get; set; }
        public Nullable<decimal> ntotalMN_ctaco { get; set; }
        public Nullable<decimal> ntotalUS_ctaco { get; set; }
        public Nullable<decimal> npago_ctaco { get; set; }
        public Nullable<int> ncode_letra { get; set; }
        public string sesta_letra { get; set; }
        public string suser_ctaco { get; set; }
        public Nullable<System.DateTime> dfech_ctaco { get; set; }
        public string susmo_ctaco { get; set; }
        public Nullable<System.DateTime> dfemo_ctaco { get; set; }
        public int ncode_cliente { get; set; }
        public int ncode_docu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTASCO_DETALLE> CTASCO_DETALLE { get; set; }
        public virtual CONFIGURACION CONFIGURACION { get; set; }
        public virtual CLIENTE CLIENTE { get; set; }
    }
}
