//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTAS_PAGAR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CTAS_PAGAR()
        {
            this.CTASPA_DETALLE = new HashSet<CTASPA_DETALLE>();
        }
    
        public long ncode_ctapa { get; set; }
        public Nullable<long> ncodeDoc_ctapa { get; set; }
        public string sdocu_ctapa { get; set; }
        public Nullable<System.DateTime> dfecta_ctapa { get; set; }
        public Nullable<System.DateTime> dfevenci_ctapa { get; set; }
        public string smone_ctapa { get; set; }
        public Nullable<decimal> ntotal_ctapa { get; set; }
        public Nullable<decimal> ntotalMN_ctapa { get; set; }
        public Nullable<decimal> ntotal_US_ctapa { get; set; }
        public Nullable<decimal> ntc_ctapa { get; set; }
        public Nullable<decimal> npago_ctapa { get; set; }
        public Nullable<int> ncode_letra { get; set; }
        public string sesta_letra { get; set; }
        public string suser_ctapa { get; set; }
        public Nullable<System.DateTime> dfech_ctapa { get; set; }
        public string susmo_ctapa { get; set; }
        public Nullable<System.DateTime> dfemo_ctapa { get; set; }
        public int ncode_docu { get; set; }
        public Nullable<long> ncode_provee { get; set; }
        public Nullable<int> ncode_banco { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTASPA_DETALLE> CTASPA_DETALLE { get; set; }
        public virtual PROVEEDOR PROVEEDOR { get; set; }
        public virtual CONFIGURACION CONFIGURACION { get; set; }
        public virtual CONFIGURACION CONFIGURACION1 { get; set; }
    }
}
