//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTASCO_DETALLE
    {
        public long ncode_ctacode { get; set; }
        public Nullable<System.DateTime> dfepago_ctacode { get; set; }
        public string sdoc_ctacode { get; set; }
        public string smone_ctacode { get; set; }
        public Nullable<decimal> ntc_ctacode { get; set; }
        public Nullable<decimal> nmonto_ctacode { get; set; }
        public Nullable<decimal> nvuelto_ctacode { get; set; }
        public string suser_tarjeta { get; set; }
        public string snro_tarjeta { get; set; }
        public string sobse_ctacode { get; set; }
        public string suser_ctacode { get; set; }
        public Nullable<System.DateTime> dfech_ctacode { get; set; }
        public string susmo_ctacode { get; set; }
        public Nullable<System.DateTime> dfemo_ctacode { get; set; }
        public long ncode_ctaco { get; set; }
        public Nullable<int> ncode_banco { get; set; }
        public int ncode_tpago { get; set; }
        public Nullable<int> ncode_tarjeta { get; set; }
        public Nullable<decimal> nmontoMN_ctacode { get; set; }
        public Nullable<decimal> nmontoUS_ctacode { get; set; }
    
        public virtual CTA_COBRAR CTA_COBRAR { get; set; }
        public virtual CONFIGURACION CONFIGURACION { get; set; }
        public virtual CONFIGURACION CONFIGURACION1 { get; set; }
    }
}
