//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCU_SERIE
    {
        public long ncode_dose { get; set; }
        public int ncode_docu { get; set; }
        public string snumeracion_dose { get; set; }
        public string susuario_dose { get; set; }
        public string sdocumento_dose { get; set; }
        public string suser_dose { get; set; }
        public Nullable<System.DateTime> dfech_dose { get; set; }
        public string susmo_dose { get; set; }
        public Nullable<System.DateTime> dfemo_dose { get; set; }
        public int ncode_local { get; set; }
    
        public virtual CONFIGURACION CONFIGURACION { get; set; }
        public virtual LOCAL LOCAL { get; set; }
    }
}
