//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCU_SERIE_USUARIO
    {
        public Nullable<long> ncode_dose { get; set; }
        public string susuario_dose { get; set; }
        public string suser_dose { get; set; }
        public Nullable<System.DateTime> dfech_dose { get; set; }
        public string susmo_dose { get; set; }
        public Nullable<System.DateTime> dfemo_dose { get; set; }
        public long ncode_docuus { get; set; }
    
        public virtual DOCU_SERIE DOCU_SERIE { get; set; }
    }
}
