//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GUIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GUIA()
        {
            this.GUIA_DETALLE = new HashSet<GUIA_DETALLE>();
        }
    
        public long ncode_guia { get; set; }
        public System.DateTime dfemov_guia { get; set; }
        public string smone_guia { get; set; }
        public decimal ntc_guia { get; set; }
        public string sobse_guia { get; set; }
        public bool besta_guia { get; set; }
        public string sserie_guia { get; set; }
        public string snume_guia { get; set; }
        public string suser_guia { get; set; }
        public Nullable<System.DateTime> dfech_guia { get; set; }
        public string susmo_guia { get; set; }
        public Nullable<System.DateTime> dfemo_guia { get; set; }
        public int ncode_tiguia { get; set; }
        public int ncode_alma { get; set; }
        public Nullable<int> ndestino_alma { get; set; }
        public string stipo_guia { get; set; }
    
        public virtual ALMACEN ALMACEN { get; set; }
        public virtual ALMACEN ALMACEN1 { get; set; }
        public virtual TIPO_GUIA TIPO_GUIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GUIA_DETALLE> GUIA_DETALLE { get; set; }
    }
}
