//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOTES
    {
        public long ncode_lote { get; set; }
        public string sdesc_lote { get; set; }
        public Nullable<System.DateTime> dfvenci_lote { get; set; }
        public Nullable<long> ncode_arti { get; set; }
        public Nullable<long> ncode_compra { get; set; }
        public Nullable<decimal> ncant_lote { get; set; }
        public Nullable<decimal> ncantdespachada_lote { get; set; }
        public Nullable<decimal> ncantrestante_lote { get; set; }
        public Nullable<bool> besta_lote { get; set; }
        public Nullable<System.DateTime> dfech_lote { get; set; }
        public string suser_lote { get; set; }
        public Nullable<System.DateTime> dfemo_lote { get; set; }
        public string susmo_lote { get; set; }
        public Nullable<int> nback_lote { get; set; }
        public string stipomovi_lote { get; set; }
        public string smodulo_confi { get; set; }
        public Nullable<int> ncode_confi { get; set; }
        public Nullable<int> ncode_alma { get; set; }
        public string sserie_lote { get; set; }
        public string snume_lote { get; set; }
        public Nullable<long> ncodeDoc_lote { get; set; }
        public Nullable<long> ncode_lotepadre { get; set; }
    
        public virtual COMPRAS COMPRAS { get; set; }
        public virtual ARTICULO ARTICULO { get; set; }
    }
}
