//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOTES
    {
        public long ncode_lote { get; set; }
        public string sdesc_lote { get; set; }
        public Nullable<System.DateTime> dfvenci_lote { get; set; }
        public Nullable<long> ncode_arti { get; set; }
        public Nullable<long> ncode_compra { get; set; }
        public Nullable<decimal> ncant_lote { get; set; }
        public Nullable<decimal> ncantdespachada_lote { get; set; }
        public Nullable<decimal> ncantrestante_lote { get; set; }
        public Nullable<bool> besta_lote { get; set; }
        public Nullable<System.DateTime> dfech_lote { get; set; }
        public string suser_lote { get; set; }
        public Nullable<System.DateTime> dfemo_lote { get; set; }
        public string susmo_lote { get; set; }
        public Nullable<int> nback_lote { get; set; }
    
        public virtual COMPRAS COMPRAS { get; set; }
        public virtual ARTICULO ARTICULO { get; set; }
    }
}
