//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MARCA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MARCA()
        {
            this.ARTICULO = new HashSet<ARTICULO>();
        }
    
        public long ncode_marca { get; set; }
        public string sdesc_marca { get; set; }
        public bool nesta_marca { get; set; }
        public string suser_marca { get; set; }
        public Nullable<System.DateTime> dfech_marca { get; set; }
        public string susmo_marca { get; set; }
        public Nullable<System.DateTime> dfemo_marca { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARTICULO> ARTICULO { get; set; }
    }
}
