//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketASP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MarketWebEntities : DbContext
    {
        public MarketWebEntities()
            : base("name=MarketWebEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ALMACEN> ALMACEN { get; set; }
        public virtual DbSet<ART_BARRA> ART_BARRA { get; set; }
        public virtual DbSet<ART_PRECIO> ART_PRECIO { get; set; }
        public virtual DbSet<ART_PROVE> ART_PROVE { get; set; }
        public virtual DbSet<ARTICULO> ARTICULO { get; set; }
        public virtual DbSet<CLASE> CLASE { get; set; }
        public virtual DbSet<CLI_DIRE> CLI_DIRE { get; set; }
        public virtual DbSet<CLIDI_CONTAC> CLIDI_CONTAC { get; set; }
        public virtual DbSet<CLIENTE> CLIENTE { get; set; }
        public virtual DbSet<CONFIGURACION> CONFIGURACION { get; set; }
        public virtual DbSet<CONTACTO> CONTACTO { get; set; }
        public virtual DbSet<FAMILIA> FAMILIA { get; set; }
        public virtual DbSet<LISTA_PRECIO> LISTA_PRECIO { get; set; }
        public virtual DbSet<MARCA> MARCA { get; set; }
        public virtual DbSet<MOVI_DETALLE> MOVI_DETALLE { get; set; }
        public virtual DbSet<PROV_CONTACTO> PROV_CONTACTO { get; set; }
        public virtual DbSet<PROVEEDOR> PROVEEDOR { get; set; }
        public virtual DbSet<TIPO_CAMBIO> TIPO_CAMBIO { get; set; }
        public virtual DbSet<TIPO_MOVIMIENTO> TIPO_MOVIMIENTO { get; set; }
        public virtual DbSet<UBIGEO> UBIGEO { get; set; }
        public virtual DbSet<UMEDIDA> UMEDIDA { get; set; }
        public virtual DbSet<MOVIMIENTO> MOVIMIENTO { get; set; }
        public virtual DbSet<KARDEX> KARDEX { get; set; }
        public virtual DbSet<VENTA_DETALLE> VENTA_DETALLE { get; set; }
        public virtual DbSet<VENTAS> VENTAS { get; set; }
    
        public virtual int Pr_tipoCambioExiste(string dfecha_tc, ObjectParameter valor)
        {
            var dfecha_tcParameter = dfecha_tc != null ?
                new ObjectParameter("dfecha_tc", dfecha_tc) :
                new ObjectParameter("dfecha_tc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_tipoCambioExiste", dfecha_tcParameter, valor);
        }
    
        public virtual ObjectResult<Pr_ConsultaArticulos_Result> Pr_ConsultaArticulos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_ConsultaArticulos_Result>("Pr_ConsultaArticulos");
        }
    
        public virtual int Pr_movimientoCrear(Nullable<System.DateTime> dfemov_movi, string smone_movi, Nullable<decimal> ntc_movi, string sobse_movi, string sserie_movi, string snume_movi, string suser_movi, Nullable<int> ncode_timovi, Nullable<int> ncode_alma, Nullable<int> ndestino_alma, string stipo_movi, ObjectParameter sw)
        {
            var dfemov_moviParameter = dfemov_movi.HasValue ?
                new ObjectParameter("dfemov_movi", dfemov_movi) :
                new ObjectParameter("dfemov_movi", typeof(System.DateTime));
    
            var smone_moviParameter = smone_movi != null ?
                new ObjectParameter("smone_movi", smone_movi) :
                new ObjectParameter("smone_movi", typeof(string));
    
            var ntc_moviParameter = ntc_movi.HasValue ?
                new ObjectParameter("ntc_movi", ntc_movi) :
                new ObjectParameter("ntc_movi", typeof(decimal));
    
            var sobse_moviParameter = sobse_movi != null ?
                new ObjectParameter("sobse_movi", sobse_movi) :
                new ObjectParameter("sobse_movi", typeof(string));
    
            var sserie_moviParameter = sserie_movi != null ?
                new ObjectParameter("sserie_movi", sserie_movi) :
                new ObjectParameter("sserie_movi", typeof(string));
    
            var snume_moviParameter = snume_movi != null ?
                new ObjectParameter("snume_movi", snume_movi) :
                new ObjectParameter("snume_movi", typeof(string));
    
            var suser_moviParameter = suser_movi != null ?
                new ObjectParameter("suser_movi", suser_movi) :
                new ObjectParameter("suser_movi", typeof(string));
    
            var ncode_timoviParameter = ncode_timovi.HasValue ?
                new ObjectParameter("ncode_timovi", ncode_timovi) :
                new ObjectParameter("ncode_timovi", typeof(int));
    
            var ncode_almaParameter = ncode_alma.HasValue ?
                new ObjectParameter("ncode_alma", ncode_alma) :
                new ObjectParameter("ncode_alma", typeof(int));
    
            var ndestino_almaParameter = ndestino_alma.HasValue ?
                new ObjectParameter("ndestino_alma", ndestino_alma) :
                new ObjectParameter("ndestino_alma", typeof(int));
    
            var stipo_moviParameter = stipo_movi != null ?
                new ObjectParameter("stipo_movi", stipo_movi) :
                new ObjectParameter("stipo_movi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_movimientoCrear", dfemov_moviParameter, smone_moviParameter, ntc_moviParameter, sobse_moviParameter, sserie_moviParameter, snume_moviParameter, suser_moviParameter, ncode_timoviParameter, ncode_almaParameter, ndestino_almaParameter, stipo_moviParameter, sw);
        }
    
        public virtual int Pr_movimientoDetaCrea(Nullable<long> ncode_arti, Nullable<decimal> ncant_movidet, Nullable<decimal> npu_movidet, string suser_movidet, Nullable<int> ncode_movi, Nullable<int> ncode_umed)
        {
            var ncode_artiParameter = ncode_arti.HasValue ?
                new ObjectParameter("ncode_arti", ncode_arti) :
                new ObjectParameter("ncode_arti", typeof(long));
    
            var ncant_movidetParameter = ncant_movidet.HasValue ?
                new ObjectParameter("ncant_movidet", ncant_movidet) :
                new ObjectParameter("ncant_movidet", typeof(decimal));
    
            var npu_movidetParameter = npu_movidet.HasValue ?
                new ObjectParameter("npu_movidet", npu_movidet) :
                new ObjectParameter("npu_movidet", typeof(decimal));
    
            var suser_movidetParameter = suser_movidet != null ?
                new ObjectParameter("suser_movidet", suser_movidet) :
                new ObjectParameter("suser_movidet", typeof(string));
    
            var ncode_moviParameter = ncode_movi.HasValue ?
                new ObjectParameter("ncode_movi", ncode_movi) :
                new ObjectParameter("ncode_movi", typeof(int));
    
            var ncode_umedParameter = ncode_umed.HasValue ?
                new ObjectParameter("ncode_umed", ncode_umed) :
                new ObjectParameter("ncode_umed", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_movimientoDetaCrea", ncode_artiParameter, ncant_movidetParameter, npu_movidetParameter, suser_movidetParameter, ncode_moviParameter, ncode_umedParameter);
        }
    
        public virtual int Pr_KardexCrea(string modulo, Nullable<int> ncode_confi, string tipo, Nullable<decimal> codigo, string usuario)
        {
            var moduloParameter = modulo != null ?
                new ObjectParameter("modulo", modulo) :
                new ObjectParameter("modulo", typeof(string));
    
            var ncode_confiParameter = ncode_confi.HasValue ?
                new ObjectParameter("ncode_confi", ncode_confi) :
                new ObjectParameter("ncode_confi", typeof(int));
    
            var tipoParameter = tipo != null ?
                new ObjectParameter("tipo", tipo) :
                new ObjectParameter("tipo", typeof(string));
    
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(decimal));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_KardexCrea", moduloParameter, ncode_confiParameter, tipoParameter, codigoParameter, usuarioParameter);
        }
    
        public virtual int Pr_KardexElimina(string modulo, Nullable<decimal> codigo)
        {
            var moduloParameter = modulo != null ?
                new ObjectParameter("modulo", modulo) :
                new ObjectParameter("modulo", typeof(string));
    
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_KardexElimina", moduloParameter, codigoParameter);
        }
    
        public virtual int Pr_movimientoElimina(Nullable<decimal> ncode_movi)
        {
            var ncode_moviParameter = ncode_movi.HasValue ?
                new ObjectParameter("ncode_movi", ncode_movi) :
                new ObjectParameter("ncode_movi", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_movimientoElimina", ncode_moviParameter);
        }
    
        public virtual int Pr_movimientoDetaElimina(Nullable<decimal> ncode_movi)
        {
            var ncode_moviParameter = ncode_movi.HasValue ?
                new ObjectParameter("ncode_movi", ncode_movi) :
                new ObjectParameter("ncode_movi", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_movimientoDetaElimina", ncode_moviParameter);
        }
    
        public virtual int Pr_movimientoEditar(Nullable<decimal> ncode_movi, Nullable<System.DateTime> dfemov_movi, string smone_movi, Nullable<decimal> ntc_movi, string sobse_movi, string sserie_movi, string snume_movi, string suser_movi, Nullable<int> ncode_timovi, Nullable<int> ncode_alma, Nullable<int> ndestino_alma, string stipo_movi, Nullable<bool> besta_movi, ObjectParameter sw)
        {
            var ncode_moviParameter = ncode_movi.HasValue ?
                new ObjectParameter("ncode_movi", ncode_movi) :
                new ObjectParameter("ncode_movi", typeof(decimal));
    
            var dfemov_moviParameter = dfemov_movi.HasValue ?
                new ObjectParameter("dfemov_movi", dfemov_movi) :
                new ObjectParameter("dfemov_movi", typeof(System.DateTime));
    
            var smone_moviParameter = smone_movi != null ?
                new ObjectParameter("smone_movi", smone_movi) :
                new ObjectParameter("smone_movi", typeof(string));
    
            var ntc_moviParameter = ntc_movi.HasValue ?
                new ObjectParameter("ntc_movi", ntc_movi) :
                new ObjectParameter("ntc_movi", typeof(decimal));
    
            var sobse_moviParameter = sobse_movi != null ?
                new ObjectParameter("sobse_movi", sobse_movi) :
                new ObjectParameter("sobse_movi", typeof(string));
    
            var sserie_moviParameter = sserie_movi != null ?
                new ObjectParameter("sserie_movi", sserie_movi) :
                new ObjectParameter("sserie_movi", typeof(string));
    
            var snume_moviParameter = snume_movi != null ?
                new ObjectParameter("snume_movi", snume_movi) :
                new ObjectParameter("snume_movi", typeof(string));
    
            var suser_moviParameter = suser_movi != null ?
                new ObjectParameter("suser_movi", suser_movi) :
                new ObjectParameter("suser_movi", typeof(string));
    
            var ncode_timoviParameter = ncode_timovi.HasValue ?
                new ObjectParameter("ncode_timovi", ncode_timovi) :
                new ObjectParameter("ncode_timovi", typeof(int));
    
            var ncode_almaParameter = ncode_alma.HasValue ?
                new ObjectParameter("ncode_alma", ncode_alma) :
                new ObjectParameter("ncode_alma", typeof(int));
    
            var ndestino_almaParameter = ndestino_alma.HasValue ?
                new ObjectParameter("ndestino_alma", ndestino_alma) :
                new ObjectParameter("ndestino_alma", typeof(int));
    
            var stipo_moviParameter = stipo_movi != null ?
                new ObjectParameter("stipo_movi", stipo_movi) :
                new ObjectParameter("stipo_movi", typeof(string));
    
            var besta_moviParameter = besta_movi.HasValue ?
                new ObjectParameter("besta_movi", besta_movi) :
                new ObjectParameter("besta_movi", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_movimientoEditar", ncode_moviParameter, dfemov_moviParameter, smone_moviParameter, ntc_moviParameter, sobse_moviParameter, sserie_moviParameter, snume_moviParameter, suser_moviParameter, ncode_timoviParameter, ncode_almaParameter, ndestino_almaParameter, stipo_moviParameter, besta_moviParameter, sw);
        }
    
        public virtual int Pr_ClienteElimina(Nullable<long> ncode_cliente, ObjectParameter sw)
        {
            var ncode_clienteParameter = ncode_cliente.HasValue ?
                new ObjectParameter("ncode_cliente", ncode_cliente) :
                new ObjectParameter("ncode_cliente", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_ClienteElimina", ncode_clienteParameter, sw);
        }
    }
}
