//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketASP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MarketWebEntities : DbContext
    {
        public MarketWebEntities()
            : base("name=MarketWebEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ART_BARRA> ART_BARRA { get; set; }
        public virtual DbSet<ART_PRECIO> ART_PRECIO { get; set; }
        public virtual DbSet<ART_PROVE> ART_PROVE { get; set; }
        public virtual DbSet<CLASE> CLASE { get; set; }
        public virtual DbSet<FAMILIA> FAMILIA { get; set; }
        public virtual DbSet<LISTA_PRECIO> LISTA_PRECIO { get; set; }
        public virtual DbSet<MARCA> MARCA { get; set; }
        public virtual DbSet<PROVEEDOR> PROVEEDOR { get; set; }
        public virtual DbSet<UMEDIDA> UMEDIDA { get; set; }
        public virtual DbSet<ARTICULO> ARTICULO { get; set; }
    }
}
