//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOVI_DETALLE
    {
        public int ncode_movidet { get; set; }
        public long ncode_arti { get; set; }
        public Nullable<decimal> ncant_movidet { get; set; }
        public Nullable<decimal> npu_movidet { get; set; }
        public string suser_movidet { get; set; }
        public Nullable<System.DateTime> dfech_movidet { get; set; }
        public string susmo_movidet { get; set; }
        public Nullable<System.DateTime> dfemo_movidet { get; set; }
        public int ncode_movi { get; set; }
        public long ncode_umed { get; set; }
    
        public virtual ARTICULO ARTICULO { get; set; }
        public virtual MOVIMIENTO MOVIMIENTO { get; set; }
        public virtual UMEDIDA UMEDIDA { get; set; }
    }
}
