//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOVI_DETALLE
    {
        public int ncode_movidet { get; set; }
        public long ncode_arti { get; set; }
        public Nullable<decimal> ncant_movidet { get; set; }
        public Nullable<decimal> npu_movidet { get; set; }
        public string suser_movidet { get; set; }
        public Nullable<System.DateTime> dfech_movidet { get; set; }
        public string susmo_movidet { get; set; }
        public Nullable<System.DateTime> dfemo_movidet { get; set; }
        public long ncode_movi { get; set; }
        public long ncode_umed { get; set; }
        public Nullable<int> nback_movidet { get; set; }
    
        public virtual ARTICULO ARTICULO { get; set; }
        public virtual MOVIMIENTO MOVIMIENTO { get; set; }
        public virtual UMEDIDA UMEDIDA { get; set; }
    }
}
