//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOVIMIENTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MOVIMIENTO()
        {
            this.MOVI_DETALLE = new HashSet<MOVI_DETALLE>();
            this.MOVI_LOTE = new HashSet<MOVI_LOTE>();
        }
    
        public long ncode_movi { get; set; }
        public System.DateTime dfemov_movi { get; set; }
        public string smone_movi { get; set; }
        public decimal ntc_movi { get; set; }
        public string sobse_movi { get; set; }
        public bool besta_movi { get; set; }
        public string sserie_movi { get; set; }
        public string snume_movi { get; set; }
        public string suser_movi { get; set; }
        public Nullable<System.DateTime> dfech_movi { get; set; }
        public string susmo_movi { get; set; }
        public Nullable<System.DateTime> dfemo_movi { get; set; }
        public int ncode_timovi { get; set; }
        public int ncode_alma { get; set; }
        public Nullable<int> ndestino_alma { get; set; }
        public string stipo_movi { get; set; }
    
        public virtual ALMACEN ALMACEN { get; set; }
        public virtual ALMACEN ALMACEN1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MOVI_DETALLE> MOVI_DETALLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MOVI_LOTE> MOVI_LOTE { get; set; }
        public virtual TIPO_MOVIMIENTO TIPO_MOVIMIENTO { get; set; }
    }
}
