//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDEN_PEDIDOS_CUOTAS
    {
        public long ncode_orpecu { get; set; }
        public Nullable<long> ncode_orpe { get; set; }
        public Nullable<System.DateTime> dfreg_orpecu { get; set; }
        public Nullable<decimal> nvalor_orpecu { get; set; }
        public Nullable<System.DateTime> dfech_orpecu { get; set; }
        public Nullable<System.DateTime> dfemo_orpecu { get; set; }
        public string suser_orpecu { get; set; }
        public string susmo_orpecu { get; set; }
    
        public virtual ORDEN_PEDIDOS ORDEN_PEDIDOS { get; set; }
    }
}
