//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDEN_COMPRAS_DETALLE
    {
        public long ncode_orcodeta { get; set; }
        public long ncode_arti { get; set; }
        public Nullable<decimal> ncant_orcodeta { get; set; }
        public Nullable<decimal> npu_orcodeta { get; set; }
        public Nullable<decimal> ndscto_orcodeta { get; set; }
        public Nullable<decimal> ndscto2_orcodeta { get; set; }
        public Nullable<decimal> nexon_orcodeta { get; set; }
        public Nullable<decimal> nafecto_orcodeta { get; set; }
        public bool besafecto_orcodeta { get; set; }
        public Nullable<int> ncode_alma { get; set; }
        public Nullable<decimal> ndsctomax_orcodeta { get; set; }
        public Nullable<decimal> ndsctomin_orcodeta { get; set; }
        public Nullable<decimal> ndsctoporc_orcodeta { get; set; }
        public Nullable<int> nback_orcodeta { get; set; }
        public Nullable<long> ncode_orco { get; set; }
        public Nullable<decimal> nsubt_orcodeta { get; set; }
        public Nullable<decimal> npuorigen_orcodeta { get; set; }
        public Nullable<decimal> ncantventa_orcodeta { get; set; }
    
        public virtual ARTICULO ARTICULO { get; set; }
        public virtual ORDEN_COMPRAS ORDEN_COMPRAS { get; set; }
    }
}
