//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDEN_COMPRAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORDEN_COMPRAS()
        {
            this.ORDEN_COMPRAS_DETALLE = new HashSet<ORDEN_COMPRAS_DETALLE>();
        }
    
        public long ncode_orco { get; set; }
        public int ncode_docu { get; set; }
        public string sseri_orco { get; set; }
        public string snume_orco { get; set; }
        public Nullable<System.DateTime> dfeorco_orco { get; set; }
        public Nullable<System.DateTime> dfevenci_orco { get; set; }
        public int ncode_cliente { get; set; }
        public Nullable<int> ncode_clidire { get; set; }
        public string smone_orco { get; set; }
        public Nullable<decimal> ntc_orco { get; set; }
        public int ncode_fopago { get; set; }
        public string sobse_orco { get; set; }
        public Nullable<decimal> nbrutoex_orco { get; set; }
        public Nullable<decimal> nbrutoaf_orco { get; set; }
        public Nullable<decimal> ndctoex_orco { get; set; }
        public Nullable<decimal> ndsctoaf_orco { get; set; }
        public Nullable<decimal> nsubex_orco { get; set; }
        public Nullable<decimal> nsubaf_orco { get; set; }
        public Nullable<decimal> nigvex_orco { get; set; }
        public Nullable<decimal> nigvaf_orco { get; set; }
        public Nullable<decimal> ntotaex_orco { get; set; }
        public Nullable<decimal> ntotaaf_orco { get; set; }
        public Nullable<decimal> ntotal_orco { get; set; }
        public Nullable<decimal> ntotalMN_orco { get; set; }
        public Nullable<decimal> ntotalUs_orco { get; set; }
        public Nullable<bool> besta_orco { get; set; }
        public Nullable<decimal> nvalIGV_orco { get; set; }
        public string suser_orco { get; set; }
        public Nullable<System.DateTime> dfech_orco { get; set; }
        public string susmo_orco { get; set; }
        public Nullable<System.DateTime> dfemo_orco { get; set; }
        public int ncode_alma { get; set; }
        public int ncode_local { get; set; }
        public Nullable<int> ncode_mone { get; set; }
        public Nullable<long> ncode_vende { get; set; }
        public Nullable<int> bcompra_orco { get; set; }
    
        public virtual ALMACEN ALMACEN { get; set; }
        public virtual CLI_DIRE CLI_DIRE { get; set; }
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual CONFIGURACION CONFIGURACION { get; set; }
        public virtual CONFIGURACION CONFIGURACION1 { get; set; }
        public virtual LOCAL LOCAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDEN_COMPRAS_DETALLE> ORDEN_COMPRAS_DETALLE { get; set; }
    }
}
