//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROFORMAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROFORMAS()
        {
            this.PROFORMA_DETALLE = new HashSet<PROFORMA_DETALLE>();
        }
    
        public long ncode_prof { get; set; }
        public int ncode_docu { get; set; }
        public string sseri_prof { get; set; }
        public string snume_prof { get; set; }
        public Nullable<System.DateTime> dfeprofo_prof { get; set; }
        public Nullable<System.DateTime> dfevenci_prof { get; set; }
        public int ncode_cliente { get; set; }
        public Nullable<int> ncode_clidire { get; set; }
        public string smone_prof { get; set; }
        public Nullable<decimal> ntc_prof { get; set; }
        public int ncode_fopago { get; set; }
        public string sobse_prof { get; set; }
        public Nullable<long> ncode_compra { get; set; }
        public Nullable<decimal> nbrutoex_prof { get; set; }
        public Nullable<decimal> nbrutoaf_prof { get; set; }
        public Nullable<decimal> ndctoex_prof { get; set; }
        public Nullable<decimal> ndsctoaf_prof { get; set; }
        public Nullable<decimal> nsubex_prof { get; set; }
        public Nullable<decimal> nsubaf_prof { get; set; }
        public Nullable<decimal> nigvex_prof { get; set; }
        public Nullable<decimal> nigvaf_prof { get; set; }
        public Nullable<decimal> ntotaex_prof { get; set; }
        public Nullable<decimal> ntotaaf_prof { get; set; }
        public Nullable<decimal> ntotal_prof { get; set; }
        public Nullable<decimal> ntotalMN_prof { get; set; }
        public Nullable<decimal> ntotalUs_prof { get; set; }
        public Nullable<bool> besta_prof { get; set; }
        public Nullable<decimal> nvalIGV_prof { get; set; }
        public string suser_prof { get; set; }
        public Nullable<System.DateTime> dfech_prof { get; set; }
        public string susmo_prof { get; set; }
        public Nullable<System.DateTime> dfemo_prof { get; set; }
        public int ncode_alma { get; set; }
        public int ncode_local { get; set; }
        public Nullable<int> ncode_mone { get; set; }
    
        public virtual ALMACEN ALMACEN { get; set; }
        public virtual CLI_DIRE CLI_DIRE { get; set; }
        public virtual CONFIGURACION CONFIGURACION { get; set; }
        public virtual CONFIGURACION CONFIGURACION1 { get; set; }
        public virtual LOCAL LOCAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROFORMA_DETALLE> PROFORMA_DETALLE { get; set; }
        public virtual CLIENTE CLIENTE { get; set; }
    }
}
