//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVEEDOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROVEEDOR()
        {
            this.ART_PROVE = new HashSet<ART_PROVE>();
            this.PROV_CONTACTO = new HashSet<PROV_CONTACTO>();
            this.COMPRAS = new HashSet<COMPRAS>();
            this.CTAS_PAGAR = new HashSet<CTAS_PAGAR>();
        }
    
        public long ncode_provee { get; set; }
        public string sdesc_prove { get; set; }
        public string sdire_prove { get; set; }
        public string sruc_prove { get; set; }
        public string sfono_prove { get; set; }
        public string sfax_prove { get; set; }
        public string smail_prove { get; set; }
        public string sobse_prove { get; set; }
        public string sweb_prove { get; set; }
        public string scontac_prove { get; set; }
        public bool nesta_prove { get; set; }
        public string scargoconta_prove { get; set; }
        public Nullable<int> bprocedencia_prove { get; set; }
        public string suser_prove { get; set; }
        public Nullable<System.DateTime> dfech_prove { get; set; }
        public string susmo_prove { get; set; }
        public Nullable<System.DateTime> dfemo_prove { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ART_PROVE> ART_PROVE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROV_CONTACTO> PROV_CONTACTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPRAS> COMPRAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTAS_PAGAR> CTAS_PAGAR { get; set; }
    }
}
