//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROV_CONTACTO
    {
        public int ncode_provcontac { get; set; }
        public long ncode_provee { get; set; }
        public int ncode_contac { get; set; }
        public Nullable<int> besta_provcontac { get; set; }
    
        public virtual CONTACTO CONTACTO { get; set; }
        public virtual PROVEEDOR PROVEEDOR { get; set; }
    }
}
