//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecetaDetalle
    {
        public long RecD_codigo { get; set; }
        public string RecD_Codclase { get; set; }
        public string RecD_CodProd { get; set; }
        public Nullable<decimal> RecD_Cantidad { get; set; }
        public string RecD_Almacen { get; set; }
        public string RecD_CodProdPadre { get; set; }
        public Nullable<int> RecD_tipo { get; set; }
        public Nullable<long> RecD_coidgoPadre { get; set; }
        public Nullable<long> Rec_codigo { get; set; }
        public Nullable<decimal> RecD_precio { get; set; }
        public Nullable<long> ncode_arti { get; set; }
        public Nullable<int> ncode_alma { get; set; }
    
        public virtual ARTICULO ARTICULO { get; set; }
        public virtual CONFIGURACION CONFIGURACION { get; set; }
        public virtual Receta Receta { get; set; }
    }
}
