//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receta
    {
        public long Rec_codigo { get; set; }
        public string Rec_descripcion { get; set; }
        public string Rec_codclase { get; set; }
        public string Rec_codProd { get; set; }
        public Nullable<decimal> Rec_cantidad { get; set; }
        public string Rec_almacen { get; set; }
        public string Rec_tipo { get; set; }
        public Nullable<decimal> Rec_costoOperativo { get; set; }
    }
}
