//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Receta()
        {
            this.RecetaDetalle = new HashSet<RecetaDetalle>();
        }
    
        public long Rec_codigo { get; set; }
        public string Rec_descripcion { get; set; }
        public string Rec_codclase { get; set; }
        public string Rec_codProd { get; set; }
        public Nullable<decimal> Rec_cantidad { get; set; }
        public string Rec_almacen { get; set; }
        public string Rec_tipo { get; set; }
        public Nullable<decimal> Rec_costoOperativo { get; set; }
        public Nullable<int> ncode_alma { get; set; }
    
        public virtual ALMACEN ALMACEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecetaDetalle> RecetaDetalle { get; set; }
    }
}
