//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUBESPECIE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SUBESPECIE()
        {
            this.ARTICULO = new HashSet<ARTICULO>();
        }
    
        public long ncode_subesp { get; set; }
        public string sdesc_subesp { get; set; }
        public Nullable<bool> nesta_subesp { get; set; }
        public string suser_subesp { get; set; }
        public Nullable<System.DateTime> dfech_subesp { get; set; }
        public string susmo_subesp { get; set; }
        public Nullable<System.DateTime> dfemo_subesp { get; set; }
        public Nullable<long> ncode_espe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARTICULO> ARTICULO { get; set; }
    }
}
