//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_CAMBIO
    {
        public System.DateTime dfecha_tc { get; set; }
        public decimal ncompra_tc { get; set; }
        public decimal nventa_tc { get; set; }
    }
}
