//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_GUIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIPO_GUIA()
        {
            this.GUIA = new HashSet<GUIA>();
        }
    
        public int ncode_tiguia { get; set; }
        public string sdesc_tiguia { get; set; }
        public bool binout_tiguia { get; set; }
        public bool btransf_tiguia { get; set; }
        public bool besta_tiguia { get; set; }
        public string stipo_tiguia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GUIA> GUIA { get; set; }
    }
}
