//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_CAMBIO
    {
        public System.DateTime dfecha_tc { get; set; }
        public decimal ncompra_tc { get; set; }
        public decimal nventa_tc { get; set; }
    }
}
