//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_MOVIMIENTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIPO_MOVIMIENTO()
        {
            this.MOVIMIENTO = new HashSet<MOVIMIENTO>();
        }
    
        public int ncode_timovi { get; set; }
        public string sdesc_timovi { get; set; }
        public bool binout_tipomovi { get; set; }
        public bool btransf_tipomovi { get; set; }
        public bool besta_tipomovi { get; set; }
        public string stipo_timovi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MOVIMIENTO> MOVIMIENTO { get; set; }
    }
}
