//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSPORTISTA
    {
        public long ncode_tran { get; set; }
        public string snomb_tran { get; set; }
        public string sappa_tran { get; set; }
        public string sapma_tran { get; set; }
        public string splaca_tran { get; set; }
        public string sdni_tran { get; set; }
        public string slicencia_tran { get; set; }
        public string suser_tran { get; set; }
        public Nullable<System.DateTime> dfech_tran { get; set; }
        public string susmo_tran { get; set; }
        public Nullable<System.DateTime> dfemo_tran { get; set; }
        public Nullable<bool> nesta_tran { get; set; }
    }
}
