//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UMEDIDA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UMEDIDA()
        {
            this.MOVI_DETALLE = new HashSet<MOVI_DETALLE>();
            this.KARDEX = new HashSet<KARDEX>();
            this.ARTICULO = new HashSet<ARTICULO>();
        }
    
        public long ncode_umed { get; set; }
        public string sdesc_umed { get; set; }
        public string ssunat_umed { get; set; }
        public string scodsunat_umed { get; set; }
        public bool nesta_umed { get; set; }
        public string suser_umed { get; set; }
        public Nullable<System.DateTime> dfech_umed { get; set; }
        public string susmo_umed { get; set; }
        public Nullable<System.DateTime> dfemo_umed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MOVI_DETALLE> MOVI_DETALLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KARDEX> KARDEX { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARTICULO> ARTICULO { get; set; }
    }
}
