//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENTAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VENTAS()
        {
            this.VENTA_DETALLE = new HashSet<VENTA_DETALLE>();
        }
    
        public long ncode_venta { get; set; }
        public int ncode_docu { get; set; }
        public string sseri_venta { get; set; }
        public string snume_venta { get; set; }
        public Nullable<System.DateTime> dfeventa_venta { get; set; }
        public Nullable<System.DateTime> dfevenci_venta { get; set; }
        public int ncode_cliente { get; set; }
        public Nullable<int> ncode_clidire { get; set; }
        public string smone_venta { get; set; }
        public Nullable<decimal> ntc_venta { get; set; }
        public int ncode_fopago { get; set; }
        public string sobse_venta { get; set; }
        public Nullable<long> ncode_compra { get; set; }
        public Nullable<long> ncode_profo { get; set; }
        public Nullable<decimal> nbrutoex_venta { get; set; }
        public Nullable<decimal> nbrutoaf_venta { get; set; }
        public Nullable<decimal> ndctoex_venta { get; set; }
        public Nullable<decimal> ndsctoaf_venta { get; set; }
        public Nullable<decimal> nsubex_venta { get; set; }
        public Nullable<decimal> nsubaf_venta { get; set; }
        public Nullable<decimal> nigvex_venta { get; set; }
        public Nullable<decimal> nigvaf_venta { get; set; }
        public Nullable<decimal> ntotaex_venta { get; set; }
        public Nullable<decimal> ntotaaf_venta { get; set; }
        public Nullable<decimal> ntotal_venta { get; set; }
        public Nullable<decimal> ntotalMN_venta { get; set; }
        public Nullable<decimal> ntotalUs_venta { get; set; }
        public Nullable<bool> besta_venta { get; set; }
        public Nullable<decimal> nvalIGV_venta { get; set; }
        public string suser_venta { get; set; }
        public Nullable<System.DateTime> dfech_venta { get; set; }
        public string susmo_venta { get; set; }
        public Nullable<System.DateTime> dfemo_venta { get; set; }
        public Nullable<int> ncode_alma { get; set; }
    
        public virtual CLI_DIRE CLI_DIRE { get; set; }
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual CONFIGURACION CONFIGURACION { get; set; }
        public virtual CONFIGURACION CONFIGURACION1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VENTA_DETALLE> VENTA_DETALLE { get; set; }
    }
}
