//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENTA_DETALLE
    {
        public long ncode_vedeta { get; set; }
        public long ncode_venta { get; set; }
        public long ncode_arti { get; set; }
        public Nullable<decimal> ncant_vedeta { get; set; }
        public Nullable<decimal> npu_vedeta { get; set; }
        public Nullable<decimal> ndscto_vedeta { get; set; }
        public Nullable<decimal> ndscto2_vedeta { get; set; }
        public Nullable<decimal> nexon_vedeta { get; set; }
        public Nullable<decimal> nafecto_vedeta { get; set; }
        public bool besafecto_vedeta { get; set; }
        public Nullable<int> ncode_alma { get; set; }
        public Nullable<decimal> ndsctomax_vedeta { get; set; }
        public Nullable<decimal> ndsctomin_vedeta { get; set; }
        public Nullable<decimal> ndsctoporc_vedeta { get; set; }
        public Nullable<int> nback_vedeta { get; set; }
        public Nullable<decimal> nsubt_vedeta { get; set; }
        public Nullable<decimal> ncantLote_vedeta { get; set; }
    
        public virtual ALMACEN ALMACEN { get; set; }
        public virtual ARTICULO ARTICULO { get; set; }
        public virtual VENTAS VENTAS { get; set; }
    }
}
